// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAWgHyUELPI0b0DSmFsKxUSnvapECew5E',
    appId: '1:217234056195:web:61afa39d0a9110b4fe9a36',
    messagingSenderId: '217234056195',
    projectId: 'kroniker-app',
    authDomain: 'kroniker-app.firebaseapp.com',
    storageBucket: 'kroniker-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_cyHqJFOuBOXTADxmhxUy0wxEAvV4_SE',
    appId: '1:217234056195:android:ef0df87187db5632fe9a36',
    messagingSenderId: '217234056195',
    projectId: 'kroniker-app',
    storageBucket: 'kroniker-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_tpYMKXY9maSneeJi95808xqnd6oQJHw',
    appId: '1:217234056195:ios:423950a4331b660afe9a36',
    messagingSenderId: '217234056195',
    projectId: 'kroniker-app',
    storageBucket: 'kroniker-app.appspot.com',
    iosClientId: '217234056195-a9939mbcrutibckhc7m204iljoovthdv.apps.googleusercontent.com',
    iosBundleId: 'com.koala.koalaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_tpYMKXY9maSneeJi95808xqnd6oQJHw',
    appId: '1:217234056195:ios:f6d71ff915a7e28afe9a36',
    messagingSenderId: '217234056195',
    projectId: 'kroniker-app',
    storageBucket: 'kroniker-app.appspot.com',
    iosClientId: '217234056195-u6ql00i5j6avpuiotac7ujkpteu488d2.apps.googleusercontent.com',
    iosBundleId: 'com.koala.koalaapp.RunnerTests',
  );
}
